version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  spark-processor:
    build: ./data-processor
    depends_on:
      - hdfs
    command: ["spark-submit", "--class", "com.example.analytics.SparkProcessor", "/opt/spark-apps/spark-processor.jar"]

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  mongodb:
    image: mongo:4.4.6
    ports:
      - "27017:27017"

  hdfs:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    environment:
      - CLUSTER_NAME=test
    volumes:
      - hdfs-data:/hadoop/dfs/name
    ports:
      - "9000:9000"

volumes:
  hdfs-data:
